
book:
  name:
    zh: 白鲸
    en: Moby Dick
  author:
    name: 赫尔曼·梅尔维尔
    nationality: 美
    born: 1819
    died: 1891
  press:

library:
  name: 杭州市图书馆
  info:
    address: 中国浙江省杭州市江干区新城商圈解放东路58号

  books:
    - name: 天才基本法
      description: 二十二岁的林朝夕在父亲确诊阿尔茨海默病这天，得知自己暗恋多年的校园男神裴之即将出国深造的消息——对方考取的学校，恰是父亲当年为她放弃的那所。
    - name: 时间的秩序
      description: 为什么我们记得过去，而非未来？时间“流逝”意味着什么？是我们存在于时间之内，还是时间存在于我们之中？卡洛·罗韦利用诗意的文字，邀请我们思考这一亘古难题——时间的本质。
    - name: 了不起的我
      description: 如何养成一个新习惯？如何让心智变得更成熟？如何拥有高质量的关系？ 如何走出人生的艰难时刻？

  post:
    - 保洁
    - 保安
    - 馆长
    - 秘书
    - 管理员

  area:
    - A区
    - B区
    - C区
    - D区

  borrow:
    A1: A1
    A2: A2
    A3: A3

  magazine:
    time:
      content: 时事政治
      price: 10
    wheels:
      content: 汽车
      price: 20



